version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies..."
      - pip install -r requirements.txt
      - apt-get update && apt-get install -y zip
  build:
    commands:
      - echo "Building the Flask app..."
      - echo "No additional build steps required for Flask."
  post_build:
    commands:
      - echo "Build completed!"
      - echo "Listing files before creating deploy.zip"
      - ls -l
      - echo "Zipping deployment package..."
      - zip -r deploy.zip *  # Zip the entire application
      - echo "Listing files"
      - ls -l
      - echo "Uploading to S3..."
      - aws s3 cp deploy.zip s3://cicd-codedeploy-cil/deploy.zip  # Replace with your S3 bucket name

artifacts:
  files:
    - deploy.zip
  discard-paths: yes
